global using Concertable.Kernel;
global using Concertable.Kernel.ValueObjects;
global using Concertable.Contracts;
global using Concertable.Contracts.Enums;
global using Concertable.B2B.Artist.Contracts;
global using Concertable.B2B.Artist.Application.DTOs;
global using Concertable.B2B.Artist.Application.Interfaces;
global using Concertable.B2B.Artist.Application.Requests;
global using Concertable.B2B.Tenant.Contracts.Enums;
