global using Concertable.Kernel;
global using Concertable.Contracts;
global using Concertable.Concert.Contracts;
global using Concertable.Concert.Domain;
global using Concertable.Contract.Contracts;
global using Concertable.Concert.Application.Interfaces;
global using Concertable.Concert.Application.DTOs;
global using Concertable.Concert.Application.Requests;
global using Concertable.Concert.Application.Responses;
