// <auto-generated />
using System;
using Concertable.B2B.Deal.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Concertable.B2B.Deal.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DealDbContext))]
    [Migration("20260718225712_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("deal")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.DealEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Deals", "deal");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Concertable.Messaging.Domain.InboxMessageEntity", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MessageId", "ConsumerName");

                    b.ToTable("Inbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.Messaging.Domain.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("NextRetryAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Outbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.DoorSplitDealEntity", b =>
                {
                    b.HasBaseType("Concertable.B2B.Deal.Domain.Entities.DealEntity");

                    b.Property<decimal>("ArtistDoorPercent")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("DoorSplitDeals", "deal");
                });

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.FlatFeeDealEntity", b =>
                {
                    b.HasBaseType("Concertable.B2B.Deal.Domain.Entities.DealEntity");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("FlatFeeDeals", "deal");
                });

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.VenueHireDealEntity", b =>
                {
                    b.HasBaseType("Concertable.B2B.Deal.Domain.Entities.DealEntity");

                    b.Property<decimal>("HireFee")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("VenueHireDeals", "deal");
                });

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.VersusDealEntity", b =>
                {
                    b.HasBaseType("Concertable.B2B.Deal.Domain.Entities.DealEntity");

                    b.Property<decimal>("ArtistDoorPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Guarantee")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("VersusDeals", "deal");
                });

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.DoorSplitDealEntity", b =>
                {
                    b.HasOne("Concertable.B2B.Deal.Domain.Entities.DealEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.B2B.Deal.Domain.Entities.DoorSplitDealEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.FlatFeeDealEntity", b =>
                {
                    b.HasOne("Concertable.B2B.Deal.Domain.Entities.DealEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.B2B.Deal.Domain.Entities.FlatFeeDealEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.VenueHireDealEntity", b =>
                {
                    b.HasOne("Concertable.B2B.Deal.Domain.Entities.DealEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.B2B.Deal.Domain.Entities.VenueHireDealEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.VersusDealEntity", b =>
                {
                    b.HasOne("Concertable.B2B.Deal.Domain.Entities.DealEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.B2B.Deal.Domain.Entities.VersusDealEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
