global using Concertable.B2B.User.Contracts;
global using Concertable.B2B.Conversations.Contracts;
global using Concertable.B2B.Conversations.Contracts.Enums;
global using Concertable.B2B.Conversations.Domain.Entities;
global using Concertable.Kernel;
global using Concertable.Kernel.ValueObjects;
global using Concertable.Kernel.Identity;
global using Concertable.Contracts;
global using Concertable.Contracts.Enums;
